// AUTOGENERATED FILE. DO NOT EDIT.

import {ObjId} from "../types" 

 export type CtfLuckynumberIdl = {
  get_flag: { user_counter: ObjId, lucky_num: number },
};

export const moduleName = "luckynumber";
